spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miro_task_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ergin
    password: ergin
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect